apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: doe25-group-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        ports:
        - containers: 8080

---
