frontend-build:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm ci
    - npm run build
    - echo "frontent-build completed successfully"
  artifacts:
    paths:
      - frontend/dist

