frontend-build:
  stage: build
  image: node:20
  script:
    - cd frontend/Volunti.Web
    - npm ci
    - npm run build
    - echo "frontent-build completed successfully"
  artifacts:
    paths:
      - frontend/Burgundy.Web/dist/
    expire_in: 1 hour 

