
stages:

  - lint
  - build
  - container-build

include:

  - local: 'lint.yml'
  - local: 'backend/build.yml'
  - local: 'backend/container-build.yml'
  - local: 'frontend/build.yml'
  - local: 'frontend/container-build.yml'

