
stages:

  - lint
  - build
  - test
  - container-build
  - deploy


default:
  tags:
    - lab-vm # runner på VM från skolan


include:

  - local: 'lint.yml'
  - local: 'backend/build.yml'
  - local: 'backend/test.yml'
  - local: 'backend/container-build.yml'
  - local: 'backend/deploy.yml'
  - local: 'frontend/build.yml'
  - local: 'frontend/test.yml'
  - local: 'frontend/container-build.yml'
  - local: 'frontend/deploy.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
