services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${IMAGE_TAG}
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=Burgundy;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      - JWT__SigningKey=${JWT__SigningKey}
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Issuer=https://api-${PUBLIC_HOST}.doe25.swarm.chas-lab.dev
      - Jwt__Audience=https://${PUBLIC_HOST}.doe25.swarm.chas-lab.dev
    networks:
      - traefik-public
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        - "traefik.http.routers.${STACK_NAME}-backend-https.rule=Host(`api-${PUBLIC_HOST}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-backend-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-backend-https.tls=true"
        - "traefik.http.routers.${STACK_NAME}-backend-https.tls.certresolver=le"
        - "traefik.http.services.${STACK_NAME}-backend.loadbalancer.server.port=8080"

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${IMAGE_TAG}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        - "traefik.http.routers.${STACK_NAME}-frontend-https.rule=Host(`${PUBLIC_HOST}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-frontend-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-frontend-https.tls=true"
        - "traefik.http.routers.${STACK_NAME}-frontend-https.tls.certresolver=le"
        - "traefik.http.services.${STACK_NAME}-frontend.loadbalancer.server.port=80"

  # mssql-init:
  #   image: busybox:latest
  #   user: root
  #   volumes:
  #     - sqldata:/var/opt/mssql
  #   command: chown -R 10001:0 /var/opt/mssql
  #   networks:
  #     - internal
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 1
  #     placement:
  #       constraints:
  #         - node.role == manager # Ensure this runs on a manager node to initialize the volume permissions

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
    networks:
      - internal
    volumes:
      - sqldata:/var/opt/mssql
    # depends_on:
    #   - mssql-init
    deploy:
      placement:
        constraints:
          - node.role == manager # specific constraint to ensure the database runs on a manager node

  adminer:
    image: adminer:latest
    networks:
      - traefik-public
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.swarm.network=traefik-public"
        # Här sätter vi en unik URL för Adminer, t.ex. db.dinstack...
        - "traefik.http.routers.${STACK_NAME}-adminer-https.rule=Host(`db-${PUBLIC_HOST}.doe25.swarm.chas-lab.dev`)"
        - "traefik.http.routers.${STACK_NAME}-adminer-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-adminer-https.tls=true"
        - "traefik.http.routers.${STACK_NAME}-adminer-https.tls.certresolver=le"
        - "traefik.http.services.${STACK_NAME}-adminer.loadbalancer.server.port=8080"
volumes:
  sqldata: {}

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay # for communication between services in the swarm
