backend-build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd backend/Burgundy.Api
    - dotnet restore
    - dotnet build --no-restore --configuration Release
<<<<<<< HEAD
    - dotnet publish --no-build --configuration Release --output ../../publish
=======
    - dotnet publish --no-build --configuration Release --output ../publish
>>>>>>> 15daec6 (ci/cd: Fixing build problem in backend)
  artifacts:
    paths:
      - backend/publish/
    expire_in: 1 hour
