# Build
FROM mcr.microsoft.com/dotnet/sdk:10 AS build
WORKDIR /src 
# COPY *.csproj ./ ??
# RUN dotnet restore ??
COPY ..
RUN

# Runtime 
FROM mcr.microsoft.com/dotnet/sdk:10 AS runtime
WORKDIR /app
COPY
EXPOSE 8080
# ENTRYPOINT ["dotnet", ".api??"]

