apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: doe25-group-13
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabel:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - '--config.file=/etc/prometheus.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.path=/prometheus'
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          volumemounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /etc/prometheus
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: prometheus-configuration
        - name: storage
          persistentVolumeClaim:
            claimname: prometheus-data

