apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: doe25-group-13
  labels:
    app: prometheus
spec:
  type: # ??
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: web
      protocol: TCP
