apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: volunti-basic-auth
  namespace: doe25-group-13
spec:
  basicAuth:
    secret: adminer-basic-auth

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: doe25-group-13
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    forceSTSHeader: true
    contentTypeNosniff: true
    referrerPolicy: "same-origin"
    contentSecurityPolicy: "default-src 'self'; script-src 'self'; object-src 'none'"
