apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-ingressroute-manager
  namespace: doe25-group-13
rules:
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes", "middlewares"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingressroute-manager
  namespace: doe25-group-13
subjects:
  - kind: ServiceAccount
    name: group-13
    namespace: doe25-group-13
roleRef:
  kind: Role
  name: traefik-ingressroute-manager
  apiGroup: rbac.authorization.k8s.io
