apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: doe25-group-13
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

-----------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: burgundy
type: Opaque
stringData:
  Jwt__SigningKey: ${JWT__SigningKey}
