apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: volunti-frontend
  namespace: doe25-group-13
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`volunti.cc.k3s.chas-lab.dev`)
      kind: Rule
      services:
        - name: volunti-frontend
          port: 80
      middlewares:
        - name: secure-headers
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: volunti-backend
  namespace: doe25-group-13
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.volunti.cc.k3s.chas-lab.dev`)
      kind: Rule
      services:
        - name: volunti-backend
          port: 80
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adminer
  namespace: doe25-group-13
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adminer.volunti.cc.k3s.chas-lab.dev`)
      kind: Rule
      services:
        - name: adminer
          port: 8080
      middlewares:
        - name: volunti-basic-auth
  tls:
    certResolver: letsencrypt
